import pyetrade
from properties import load_properties

"""
Run this to generate the tokens dict you will paste into the other files here that access the API.
You need to click on the URL and get the verifier code, and enter it back here.
"""

"""
After registering, you see this at the top of the page.

Individual Consumer Key
We see you already have an active key, here are the details below:
Your active SANDBOX API key is: 6de...f59, and secret is: 06b...2ee.
Your active PROD API key is: 86b...9ef, and secret is: bb7...0c2.
"""

# Load properties from etrade.properties file
props = load_properties()

def get_tokens():
    # Get properties from the file
    properties = load_properties()
    consumer_key = properties.get('consumer_key')
    consumer_secret = properties.get('consumer_secret')

    oauth = pyetrade.ETradeOAuth(consumer_key, consumer_secret)
    print(oauth.get_request_token())  # Use the printed URL

    verifier_code = input("Enter verification code: ")
    tokens = oauth.get_access_token(verifier_code)

    print(f"tokens = {tokens}")

    # Save tokens to a file
    with open('etrade_tokens.py', 'w') as f:
        f.write("# This file is auto-generated by tokens.py\n")
        f.write("# Do not edit manually\n\n")
        f.write(f"tokens = {tokens}\n")

    print(f"Tokens saved to etrade_tokens.py")


if __name__ == '__main__':
    get_tokens()
